### ISSUE TITLE
Unchecked exception in render manager.

### ISSUE THREAD

**Issue by b26x** [ThatRedox/ChunkyClPlugin#20]
When using the plugin the following error occurs:

Unchecked exception in render manager.
java.lang.ArrayIndexOutOfBoundsException: Index 65536 out of bounds for length 65536
	at chunkycl.GpuRayTracer.generateSky(GpuRayTracer.java:549)
	at chunkycl.AbstractOpenClRenderer.sceneReset(AbstractOpenClRenderer.java:38)
	at se.llbit.chunky.renderer.DefaultRenderManager.run(DefaultRenderManager.java:288)

**Comment by ThatRedox** [comment]
Duplicate of #16.
