### ISSUE TITLE
What should i do?

### ISSUE THREAD

**Issue by Aspector1** [ThatRedox/ChunkyClPlugin#27]
**I don't see ChunkyCL in the Renderer list**

The plugin ChunkyCl was developed for Chunky 2.4.0 but this is Chunky 2.4.1 - it may not work properly.
OpenCL Devices:
  [0] NVIDIA GeForce GTX 1660

Using: NVIDIA GeForce GTX 1660
       OpenCL 3.0 CUDA
2 errors generated.
Plugin ChunkyClPlugin.jar failed to load.
org.jocl.CLException: CL_BUILD_PROGRAM_FAILURE
Build log for device 0:
<kernel>:328:61: error: passing '__generic float *' to parameter of type 'float *' changes address space of pointer
            float t1 = aabbIntersectDist(origin, direction, (float*)(node+1));
                                                            ^~~~~~~~~~~~~~~~
<kernel>:26:66: note: passing argument to parameter 'bounds' here
float aabbIntersectDist(float3 *origin, float3 *direction, float bounds[6]);
                                                                 ^
<kernel>:330:61: error: passing '__generic float *' to parameter of type 'float *' changes address space of pointer
            float t2 = aabbIntersectDist(origin, direction, (float*)(node+1));
                                                            ^~~~~~~~~~~~~~~~
<kernel>:26:66: note: passing argument to parameter 'bounds' here
float aabbIntersectDist(float3 *origin, float3 *direction, float bounds[6]);
                                                                 ^

        at org.jocl.CL.clCompileProgram(CL.java:11994)
        at chunkycl.KernelLoader.loadProgram(KernelLoader.java:38)
        at chunkycl.GpuRayTracer.<init>(GpuRayTracer.java:151)
        at chunkycl.GpuRayTracer.getTracer(GpuRayTracer.java:175)
        at chunkycl.AbstractOpenClRenderer.<init>(AbstractOpenClRenderer.java:20)
        at chunkycl.OpenClRenderer.<init>(OpenClRenderer.java:17)
        at chunkycl.ChunkyCl.attach(ChunkyCl.java:26)
        at se.llbit.chunky.main.Chunky.lambda$loadPlugins$5(Chunky.java:269)
        at se.llbit.chunky.plugin.ChunkyPlugin.load(ChunkyPlugin.java:90)
        at se.llbit.chunky.main.Chunky.loadPlugins(Chunky.java:259)
        at se.llbit.chunky.main.Chunky.main(Chunky.java:213)

**Comment by Aspector1** [comment]
Actually, never mind. Everything worked fine on version 2.5.0.
