### ISSUE TITLE
Unchecked exception in render manager.

### ISSUE THREAD

**Issue by Peregrine05** [ThatRedox/ChunkyClPlugin#31]
Unchecked exception in render manager.
java.lang.NoSuchMethodError
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)

**Comment by ThatRedox** [comment]
Duplicate of #33? Not enough information. Probably fixed.
